In [4]:
from sklearn.datasets import make_classification
import numpy as np

In [54]:
x, y = make_classification(n_samples=10,n_features=10,n_classes=3, n_informative=3)
print(y)

[2 2 0 0 0 2 1 0 1 1]


In [57]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=5)
for train_index, test_index in kf.split(x, y):
    print("TRAIN:", train_index, "TEST:", test_index)
    #print(x[train_index], x[test_index])
    #print(y[train_index], y[test_index])

TRAIN: [2 3 4 5 6 7 8 9] TEST: [0 1]
TRAIN: [0 1 4 5 6 7 8 9] TEST: [2 3]
TRAIN: [0 1 2 3 6 7 8 9] TEST: [4 5]
TRAIN: [0 1 2 3 4 5 8 9] TEST: [6 7]
TRAIN: [0 1 2 3 4 5 6 7] TEST: [8 9]


In [40]:
from sklearn.model_selection import GroupKFold
gkf = GroupKFold(n_splits=5)
groups = np.array([1,2,2,3,3,4,10,5,7,6])
for train_index, test_index in gkf.split(x, y, groups):
    print("TRAIN:", train_index, "TEST:", test_index)

TRAIN: [0 1 2 5 6 7 8 9] TEST: [3 4]
TRAIN: [0 3 4 5 6 7 8 9] TEST: [1 2]
TRAIN: [0 1 2 3 4 5 8 9] TEST: [6 7]
TRAIN: [0 1 2 3 4 6 7 9] TEST: [5 8]
TRAIN: [1 2 3 4 5 6 7 8] TEST: [0 9]


In [66]:
from sklearn.model_selection import StratifiedKFold
skfold = StratifiedKFold(n_splits=3)
for train_index, test_index in skfold.split(x, y):
     print("TRAIN:", train_index, "TEST:", test_index)
     print(y[train_index])
     print(y[test_index])

TRAIN: [1 4 5 7 8 9] TEST: [0 2 3 6]
[2 0 2 0 1 1]
[2 0 0 1]
TRAIN: [0 2 3 5 6 7 9] TEST: [1 4 8]
[2 0 0 2 1 0 1]
[2 0 1]
TRAIN: [0 1 2 3 4 6 8] TEST: [5 7 9]
[2 2 0 0 0 1 1]
[2 0 1]


In [61]:
from sklearn.model_selection import LeaveOneOut
loo = LeaveOneOut()
for train_index, test_index in loo.split(x, y):
    print("TRAIN:", train_index, "TEST:", test_index)

TRAIN: [1 2 3 4 5 6 7 8 9] TEST: [0]
TRAIN: [0 2 3 4 5 6 7 8 9] TEST: [1]
TRAIN: [0 1 3 4 5 6 7 8 9] TEST: [2]
TRAIN: [0 1 2 4 5 6 7 8 9] TEST: [3]
TRAIN: [0 1 2 3 5 6 7 8 9] TEST: [4]
TRAIN: [0 1 2 3 4 6 7 8 9] TEST: [5]
TRAIN: [0 1 2 3 4 5 7 8 9] TEST: [6]
TRAIN: [0 1 2 3 4 5 6 8 9] TEST: [7]
TRAIN: [0 1 2 3 4 5 6 7 9] TEST: [8]
TRAIN: [0 1 2 3 4 5 6 7 8] TEST: [9]


In [44]:
parameters ={'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100],
     'criterion' : ['gini', 'entropy'],
     'max_features': [0.3,0.5,0.7,0.9],
     'min_samples_leaf': [3,5,7,10,15],
     'min_samples_split': [2,5,10],
     'n_estimators': [50,100,200,400,600]}
from sklearn.model_selection import ParameterGrid
params= ParameterGrid(parameters)
print('Combinations:',len(params))

Combinations: 6000


In [32]:
#cross val predict
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_predict
from sklearn.svm.classes import SVC

X = np.array([[0], [1], [2], [3], [4]])
labels = np.array(['a', 'a', 'a', 'b', 'b'])

cv = KFold(n_splits=3)
clf = SVC()
y_cross_val_predict = cross_val_predict(clf, X, labels, cv=cv)
print("predicted labels by cross_val_predict:", y_cross_val_predict)

predicted labels by cross_val_predict: ['b' 'b' 'a' 'b' 'a']


In [33]:
for train_index, test_index in cv.split(labels):
    print(train_index)

[2 3 4]
[0 1 4]
[0 1 2 3]


In [25]:
from sklearn.model_selection import cross_val_score
y_cross_val_score = cross_val_score(clf, X, labels, cv=cv)
print(y_cross_val_score)

[0. 1. 0.]


In [52]:
x

array([[ 7.28269246e-01, -1.98210076e+00, -3.59680841e-01,
         6.61671617e-01, -1.93407640e+00,  5.59373679e-01,
         1.23701819e+00, -1.40151477e+00,  2.57566641e+00,
         9.07806548e-02],
       [-8.71442718e-01, -9.30124107e-01,  2.99142534e-01,
        -2.24219911e+00, -5.60072709e-01,  2.88697643e+00,
         9.31240179e-01, -8.14314589e-01,  2.57673345e+00,
         2.97069243e-01],
       [ 1.01909032e+00, -1.71408652e+00, -2.39092021e-01,
         4.52999894e-01, -8.95351121e-01,  8.79491854e-01,
         2.26852907e+00, -1.32165149e-01,  1.62862197e+00,
        -9.85311479e-02],
       [-1.09048412e+00,  1.48170223e+00,  6.52213791e-01,
        -6.24629216e-01,  6.43696471e-01, -5.78816822e-01,
         8.66991601e-01,  2.80503080e-02, -1.14186455e+00,
        -1.98900866e+00],
       [-2.29285796e-01, -1.18609643e-01, -2.44070364e-01,
         1.75092078e+00,  4.08826003e-01, -1.45401397e+00,
        -4.60903006e-01,  8.19791493e-01, -1.42268342e+00,
        -5.

In [ ]:

cross_validate
GridsearchCV
RandomizedSearchCV