In [19]:
import numpy as np
np.set_printoptions(threshold=np.nan)  #print entire array

In [31]:
#Array creation
c = np.array([1,2,4,5])
a = np.array( [ [1,2], [3,4] ], dtype=complex )
print(a)
print("shape: ", a.shape)
print("size: ", a.size)
print("dimensions: ", a.ndim)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
shape:  (2, 2)
size:  4
dimensions:  2


In [50]:
#Arrays with initial placeholder content. 
print('zeros\n', np.zeros((2,5)))
print('zeros like\n', np.zeros_like(a)) #Return an array of zeros with shape and type of input.
print('ones\n',np.ones((3,6), dtype=np.int16))  #ones_like
print('empty\n',np.empty((2,3))) #empty like
print('full\n',np.full((2, 2), np.inf)) #full_like

zeros
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
zeros like
 [[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]
ones
 [[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
empty
 [[3.43644418e+179 1.76002023e-076 2.70289128e-056]
 [2.36307419e+180 9.45708167e-308 0.00000000e+000]]
full
 [[inf inf]
 [inf inf]]


In [54]:
print(np.arange( 10, 30, 5))
c = np.arange(24).reshape(2,3,4)
print(c)
c.cumsum(axis=1)

[10 15 20 25]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


array([[[ 0,  1,  2,  3],
        [ 4,  6,  8, 10],
        [12, 15, 18, 21]],

       [[12, 13, 14, 15],
        [28, 30, 32, 34],
        [48, 51, 54, 57]]], dtype=int32)

In [57]:
#Return evenly spaced numbers over a specified interval.
arr = np.linspace(1, 20, num=20, endpoint=True)
print(arr)
x = np.linspace( 0, 2*np.pi, 10)  
print(x)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]
[0.         0.6981317  1.3962634  2.0943951  2.7925268  3.4906585
 4.1887902  4.88692191 5.58505361 6.28318531]


In [66]:
#Shape Manipulation
print(arr.reshape(5,-1))    # -1 other dimensions are automatically calculated
arr.resize(2,10) # modifies the array itself
print(arr)
print(arr.ravel())  # returns the array, flattened
print(arr.T) # transpose

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]
 [17. 18. 19. 20.]]
[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]
[[ 1. 11.]
 [ 2. 12.]
 [ 3. 13.]
 [ 4. 14.]
 [ 5. 15.]
 [ 6. 16.]
 [ 7. 17.]
 [ 8. 18.]
 [ 9. 19.]
 [10. 20.]]
